defaults:
  - model: anti_spoofing
  - writer: wandb
  - metrics: example
  - datasets: anti_spoofing
  - dataloader: anti_spoofing
  - transforms: anti_spoofing
  - _self_

paths:
  data_root: ???

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.AntiSpoofingLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: false
  monitor: "off"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
