train:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.anti_spoofing.WaveformToSpectrogram
        n_fft: 1724
        win_length: 1724
        hop_length: 130
        power: 2.0
        normalized: false
        window_fn:
          _target_: torch.blackman_window
          _partial_: true
      - _target_: src.transforms.anti_spoofing.TrimPadTransform
        size_to_crop_to: 600
        random_crop: true

inference:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.anti_spoofing.WaveformToSpectrogram
        n_fft: 1724
        win_length: 1724
        hop_length: 130
        power: 2.0
        normalized: false
        window_fn:
          _target_: torch.blackman_window
          _partial_: true
      - _target_: src.transforms.anti_spoofing.TrimPadTransform
        size_to_crop_to: 600
        random_crop: false
